name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          cargo install --verbose --path .
          mkdir ~/build
          mv ~/.cargo/bin/bwrapman ~/build/${{ github.event.repository.name }}-${{ github.ref_name }}-amd64

      - name: Compress via Zstd
        run: zstd ~/build/*

      - name: Generate Checksums
        run: sha256sum ~/build/*zst > ~/build/SHA256SUMS.txt

      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run:
          gh release -R ${{ github.repository }} create ${{ github.ref_name }} -t ${{ github.ref_name }} ~/build/SHA256SUMS.txt ~/build/*zst
